name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: sanjibansg/substrait-fiddle-backend
        ref: dev
        token: ${{ secrets.SUBSTRAIT_FIDDLE_BACKEND }}

    - name: Build and deploy backend
      run: |
        docker build -t substrait-fiddle-backend .
        docker run -d -p 9090:9090 substrait-fiddle-backend

    - name: Checkout client code
      uses: actions/checkout@v3

    - name: Cypress run
      uses: cypress-io/github-action@v5.x.x
      with:
          start: npm run preview
